name: algorand_json
description: A collection of JSON related operations for the Algorand blockchain
version: 0.0.3
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/algorand-json
issue_tracker: https://github.com/RootSoft/algorand-json/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # HTTP & REST
  dio: ^5.5.0+1

  # JSON
  jsontool: ^2.1.0

dev_dependencies:
  # Testing framework
  test: ^1.25.8

  flutter_lints: ^4.0.0